import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <div>
      <Head>
        <title>サンプル</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <ol>
          <li><Link href="/somei_juku_sample">ソメイ塾</Link></li>
        </ol>
      </main>
    </div>
  )
}
