import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>サンプル</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      <div className="row">
        <div className="col">
          Column1
        </div>
        <div className="col">
          Column2
        </div>
        <div className="col">
          Column3
        </div>
      </div>
      </main>
    </div>
  )
}
