import Head from 'next/head'
import { Rounded } from '../../components/Buttons'
import { Card } from '../../components/Cards'
import { Footer, Header } from '../../components/Sections'
import { Slider, SliderItem } from '../../components/Slider'

const Grids = () => {
  return (
    <>
      <Head>
        <title>サンプル</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>作例</h1>
        <p />
        <h3>Slider</h3>
        <Slider>
          <SliderItem><Card /></SliderItem>
          <SliderItem><Card /></SliderItem>
          <SliderItem><Card /></SliderItem>
        </Slider>
        <p />
        <h3>Grid</h3>
        <div><Rounded href="https://getbootstrap.jp/docs/5.0/layout/grid/">Bootstrap</Rounded>を参考に.</div>
        <div className="row g-3">
          <div className="col">
            <Card />
          </div>
          <div className="col">
            <Card />
          </div>
          <div className="col">
            <Card />
          </div>
          <div className="col">
            <Card />
          </div>
        </div>
      </main>
    </>
  )
}

export default Grids